package hu.open.assistant.rf.graphical;

import hu.open.assistant.commons.graphical.task.TaskName;

public enum RfTaskName implements TaskName {
    PREPARE_BACKUP_CREATE,
    PREPARE_BACKUP_RESTORE,
    PREPARE_CMU_DATABASES,
    PREPARE_CMU_STATIONS,
    PREPARE_CMW_DATABASES,
    PREPARE_CMW_STATIONS,
    PREPARE_DATABASES_WITH_JUMP,
    PREPARE_DATABASES_WITH_TRANSFER,
    PREPARE_DATABASE_SAVE,
    PREPARE_DATABASE_SYNC,
    PREPARE_EQUIPMENTS,
    PREPARE_EQUIPMENTS_EDIT,
    PREPARE_EQUIPMENTS_EDIT_CHECKED,
    PREPARE_PRELOAD,
    PREPARE_PROFILE_CREATE,
    PREPARE_REPORTS,
    PREPARE_REPORT_SEARCH,
    PREPARE_SOURCE_FOLDERS,
    SHOW_OPERATOR_GRAPH,
    WRITE_PROFILES_TO_ALL,
    WRITE_PROFILES_TO_TARGET,
}
